void    nd_devs_init(void);
uae_u32 nd_io_lget(uaecptr addr);
uae_u32 nd_io_wget(uaecptr addr);
uae_u32 nd_io_bget(uaecptr addr);
void    nd_io_lput(uaecptr addr, uae_u32 l);
void    nd_io_wput(uaecptr addr, uae_u32 w);
void    nd_io_bput(uaecptr addr, uae_u32 b);
uae_u32 nd_ramdac_lget(uaecptr addr);
uae_u32 nd_ramdac_wget(uaecptr addr);
uae_u32 nd_ramdac_bget(uaecptr addr);
void    nd_ramdac_lput(uaecptr addr, uae_u32 l);
void    nd_ramdac_wput(uaecptr addr, uae_u32 w);
void    nd_ramdac_bput(uaecptr addr, uae_u32 b);
uae_u32 nd_dp_lget(uaecptr addr);
void    nd_dp_lput(uaecptr addr, uae_u32 b);
bool    nd_dbg_cmd(const char* buf);
void    nd_set_blank_state(int src, bool state);
